# Generated by Django 5.2.17 on 2026-09-28 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='business_name',
            field=models.CharField(default='Swiftlot', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(blank=True, default='KES', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Use a three-letter currency code, for example USD.')]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='0111506710', max_length=40),
        ),
    ]
