# Generated by Django 5.2.17 on 2026-09-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0002_alter_sitesettings_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatedocument',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
