# Generated by Django 5.2.17 on 2026-09-29 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0003_privatedocument_scanned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='asking_price_at_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
